; logger.conf — Asterisk logging
[general]
exec_after_rotate=gzip -9 ${filename}.2

[logfiles]
console => notice,warning,error
/var/log/asterisk/full => notice,warning,error,debug,verbose
/var/log/asterisk/error => error
